matrix:
  include:
    - name: "Python 3.8.2 on Windows"
      os: windows           # Windows 10
      language: shell       # 'language: python' is an error on Travis CI Windows
      cache: pip
      before_install:
        - choco install python --version 3.8.2
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov         
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  on:
    branch: gh-pages
