lanauge: node_js
node_js: 
- 11.6.0
cache: yarn
install:
- yarn install
script: 
- yarn test
- yarn run build 
deply: 
provider: pages
skip-cleanup: true
github_token: $GITHUB_TOKEN
on: 
branch: master
